(require 'org)
(require 'org-timetracker)

(setq org-hide-leading-stars t)
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
(defun inbox ()
  (interactive)
  (find-file "~/projects/org/todo.org"))
(define-key global-map "\C-ca" 'org-agenda)
(setq org-todo-keywords '("TODO(t)" "STARTED(s)" "WAITING(w)" "DONE(d)"))
(setq org-agenda-files '("~/projects/org/todo.org" "~/projects/org/todo.org_archive"))
; (setq org-agenda-include-diary t)
(setq org-agenda-include-all-todo t)
(setq org-agenda-start-on-weekday nil)
(setq org-directory "~/projects/org")

(add-to-list 'load-path "~/.emacs.d/lisp/remember-2.0")
(require 'remember-autoloads)
(setq org-directory "~/projects/org/")
(setq org-default-notes-file (concat org-directory "todo.org"))
(setq org-remember-templates
      '((?t "* %?\n  %i\n  %a" "~/projects/org/todo.org" "Inbox")))
(setq remember-annotation-functions '(org-remember-annotation))
(setq remember-handler-functions '(org-remember-handler))
(add-hook 'remember-mode-hook 'org-remember-apply-template)
(define-key global-map "\C-cr" 'org-remember)

(provide 'my-org)
