(add-to-list 'load-path (expand-file-name "~/.emacs.d/my-lisp"))

(require 'my-package)
(require 'my-generic)
(require 'my-theme)
(require 'my-w3m)
(require 'my-modes)
(require 'my-text-mode)
(require 'my-objc-mode)
(require 'my-clisp)
(require 'my-shells)
(require 'my-org)
(require 'my-erc)
(require 'my-tramp)
(require 'my-fullscreen)
(require 'my-ispell)
(require 'my-uniquify)
; (require 'my-bbdb)
(require 'my-ido)
(require 'my-windows)
(require 'my-markdown)
(require 'my-proofgeneral)
(require 'my-scala)

(if (file-exists-p "~/.emacs.d/my-wanderlust.el")
    (require 'my-wanderlust))

(require 'my-server)
